apiVersion: apps/v1

kind: Deployment

metadata:

  name: gateway

  namespace: fx

spec:

  replicas: 1

  selector:

    matchLabels:

      app: gateway

  template:

    metadata:

      labels:

        app: gateway

    spec:

      containers:

        - name: gateway

          image: fx/gateway:dev

          imagePullPolicy: IfNotPresent

          ports:

            - containerPort: 8080

          readinessProbe:

            httpGet: { path: /actuator/health, port: 8080 }

            initialDelaySeconds: 5

            periodSeconds: 5

          livenessProbe:

            httpGet: { path: /actuator/health, port: 8080 }

            initialDelaySeconds: 10

            periodSeconds: 10

---

apiVersion: v1

kind: Service

metadata:

  name: gateway

  namespace: fx

spec:

  selector:

    app: gateway

  ports:

    - name: http

      port: 8080

      targetPort: 8080

  # ClusterIP is fine; we'll port-forward for local access

  type: ClusterIP
 
