apiVersion: apps/v1

kind: Deployment

metadata:

  name: order-service

  namespace: fx

spec:

  replicas: 1

  selector:

    matchLabels:

      app: order-service

  template:

    metadata:

      labels:

        app: order-service

    spec:

      containers:

        - name: order-service

          image: fx/order-service:dev

          imagePullPolicy: IfNotPresent

          ports:

            - containerPort: 8082

          readinessProbe:

            httpGet: { path: /actuator/health, port: 8082 }

            initialDelaySeconds: 5

            periodSeconds: 5

          livenessProbe:

            httpGet: { path: /actuator/health, port: 8082 }

            initialDelaySeconds: 10

            periodSeconds: 10

---

apiVersion: v1

kind: Service

metadata:

  name: order-service

  namespace: fx

spec:

  selector:

    app: order-service

  ports:

    - name: http

      port: 8082

      targetPort: 8082
 
