# Kubernetes API version for Deployments
apiVersion: apps/v1
# The kind of Kubernetes object being defined
kind: Deployment
# Standard object metadata
metadata:
  # Name of the Deployment
  name: quote-service
  # Target namespace
  namespace: fx
# Desired state of the Deployment
spec:
  # Number of pod replicas
  replicas: 1
  # How to identify pods managed by this Deployment
  selector:
    matchLabels:
      app: quote-service
  # Pod template used for creating pods
  template:
    metadata:
      # Labels applied to pods; must match the selector
      labels:
        app: quote-service
    spec:
      containers:
        - name: quote-service
          # Container image to run
          image: fx/quote-service:dev
          # Pull only if the image is not present locally
          imagePullPolicy: IfNotPresent
          # Ports exposed by the container
          ports:
            - containerPort: 8081
          # Readiness: when passing, pod can receive traffic
          readinessProbe:
            httpGet: { path: /actuator/health, port: 8081 }
            initialDelaySeconds: 5
            periodSeconds: 5
          # Liveness: when failing, container is restarted
          livenessProbe:
            httpGet: { path: /actuator/health, port: 8081 }
            initialDelaySeconds: 10
            periodSeconds: 10

---
# Kubernetes API version for Services
apiVersion: v1
# The kind of Kubernetes object being defined
kind: Service
metadata:
  # Service name
  name: quote-service
  # Target namespace
  namespace: fx
spec:
  # Route traffic to pods with this label
  selector:
    app: quote-service
  # Service ports exposed internally in the cluster
  ports:
    - name: http
      port: 8081
      targetPort: 8081
# Service type not specified; defaults to ClusterIP
